server:
  port: 8089
  servlet:
    context-path: /practice-bom
    session:
      timeout: PT3M
      cookie:
        secure: true

spring:
  application:
    name: practice-provide-service
  cloud:
    nacos:
      discovery:
        group: PRACTICE_PROVIDE_GROUP
      config:
        group: PRACTICE_CONFIG_GROUP
        server-addr: 127.0.0.1:8848
        file-extension: yml
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}

dubbo:
  application:
    name: practice-provide-dubbo-server
  protocol:
    name: tri
    port: -1
    accesslog: true
  registry:
    id: dubbo-provide
    address: nacos://127.0.0.1:8848
    register-mode: instance/interface/all
  config-center:
    address: nacos://127.0.0.1:8848
  metadata-report:
    address: nacos://127.0.0.1:8848

logging:
  level:
    com.practice.bom: debug

