server:
  port: 8088
  servlet:
    context-path: /practice-bom
    session:
      timeout: PT3M
      cookie:
        secure: true

spring:
  application:
    name: ractice-bom
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000

logging:
  level:
    com.practice.bom: debug

